# Backend Dockerfile
FROM node:20-alpine

WORKDIR /app

# Install dependencies required for Puppeteer
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    nodejs \
    yarn

# Tell Puppeteer to skip installing Chrome. We'll be using the installed package.
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Copy backend files
COPY backend/package*.json ./
RUN npm install

COPY backend/ ./

EXPOSE 5002

CMD ["npm", "start"]